### PR TITLE
feat(file): search over all configured stemmings

### PR DESCRIPTION
**Pull request by Yelinz**
This prevents files from being not findable when there is no content or a wrong language is detected.

This might make the search a little slower, as were not filtering for the language anymore. But files can always be found, even if the language which tika detected it not in the `LANGUAGE` setting.

### CODE REVIEW

**Comment by winged** [comment]
Change LGTM, but what was the reason again to do this in the Viewset and not in the filterset?

**Comment by Yelinz** [comment]
> Change LGTM, but what was the reason again to do this in the Viewset and not in the filterset?

i dont think there was a specific reason, should I move the logic?

**Comment by winged** [comment]
> > Change LGTM, but what was the reason again to do this in the Viewset and not in the filterset?
> 
> i dont think there was a specific reason, should I move the logic?

I think it'd be cleaner. But let's keep it here and do a clean refactor PR later, to keep the diff reasonable

**Review by winged — APPROVED** [review]
Nice work, LGTM! We'll need to keep an eye on performance though, filtering across all languages may be problematic as it will multiply the workload for the DB

**Pull request merged**
